title: 黃帷凱的作品集
author: Brain Huang
email: huang950606@gmail.com
description: >-
  這是我的線上藝廊，有著過去我執行過的專案或是我滿意的作品，如果你對我的內容感興趣，或是想要交流，歡迎與我聯絡。
  其中涵蓋風景、人像、婚禮、各式活動紀錄，其中也在嘗試體育攝影。

social:
  twitter: 
  facebook: 
  instagram: weeeei_k
  github: 
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
