title: 黃帷凱的作品集
author: Brain Huang
email: huang950606@gmail.com
description: >-
  這是我的作品集，想打造成我的線上藝廊，目前還在測試中。

social:
  twitter: 
  facebook: 
  instagram: weeeei_k
  github: 
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
